---

- hosts: all
  become: true
  pre_tasks:

  - name: updates repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  tasks:

  - name: add ssh key for allen
    tags: always
    authorized_key:
      user: allen
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCMNouBxXNl4o+Cpo6c3BKW0QN28pXIvC0Rrf8U18OE9HwFMRppBzPcAA672uKnB3D1i2B+sN6qHHjkZu7rSMc0oYHjJWCGLHLBPhd3cKP1UftW7CHpYPEbt6utA887Tz/HiSQzBZo/V1xCCdk/sfwEEbB20VX7uwZXa/nVstsiT+A9M2o4SFKOkRzuxCqHfNYa8DYBgLF2ueAleKflkVudvuikOvU4hUDkGyUp2hjAKQp1MgEmc5ZEDkzxGJ2mKAl8PNr6zyKW26t3BpHjTpBuL9+B1Q84k13FAuQ2gdzsNxBDATVVPLSezs1nLeuEjBscFHRqGHQwOKgWv23tmF/e6Ve1WaAYCmtcpLLgjdzmm3pG0WobAlY6dcKJmw1PzLXICkNiliiNoWYxwe/SJ7MwRGYYZr2y0PhDImXUeEnIZ/laf/H4u8i35R50EQo+6EkW0T3eDnZUAEdJuu/FI0qpDvFhUoueH5qgjEhs79YJtDW8w9A2hqxPB9HwGb1wYzM= allen@allens-pc>"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "ubuntu"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 

- hosts: db_servers
  become: true
  tags:
    - db
    - mariadb
    - ubuntu
  tasks:
    - name: Install MariaDB on Ubuntu and update apt package cache
      apt:
        update_cache: yes

    - name: Install MariaDB server and client packages
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes






